### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by rainandwind1** [SiyuanLee/LESSON#1]
Hello, bro , error arise  when i run "python train_hier_sac.py" in terminal 

```
HRL_code\Lesson\LESSON-master>python train_hier_sac.py
path train_hier_sac.py !!!
[2021-05-08 15:29:34,740] Making new env: AntMaze1-v1
D:\Anaconda\envs\AntEnv\lib\site-packages\gym\envs\registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Warning: b'XML parse error at line 0, column 0:\nFailed to open file\n'
Traceback (most recent call last):
  File "train_hier_sac.py", line 71, in <module>
    launch(args)
  File "train_hier_sac.py", line 21, in launch
    env = gym.make(args.env_name)
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\envs\registration.py", line 161, in make
    return registry.make(id)
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\envs\registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "D:\2020Grade_three\2021_grade_proj\HRL_code\Lesson\LESSON-master\goal_env\mujoco\create_maze_env.py", line 203, in create_maze_env
    gym_env = cls(**gym_mujoco_kwargs)
  File "D:\2020Grade_three\2021_grade_proj\HRL_code\Lesson\LESSON-master\goal_env\mujoco\maze_env.py", line 231, in __init__
    self.wrapped_env = model_cls(*args, file_path=file_path, **kwargs)
  File "D:\2020Grade_three\2021_grade_proj\HRL_code\Lesson\LESSON-master\goal_env\mujoco\ant.py", line 51, in __init__
    mujoco_env.MujocoEnv.__init__(self, file_path, 10)
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\envs\mujoco\mujoco_env.py", line 28, in __init__
    self.model = mujoco_py.MjModel(fullpath)
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\mujoco_py\mjcore.py", line 34, in __init__
    data_ptr = mjlib.mj_makeData(model_ptr)
OSError: exception: access violation reading 0x0000000000000004
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\utils\closer.py", line 67, in close
    closeable.close()
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\core.py", line 167, in close
    self.render(close=True)
  File "D:\2020Grade_three\2021_grade_proj\HRL_code\Lesson\LESSON-master\goal_env\mujoco\maze_env.py", line 492, in render
    return self.wrapped_env.render(*args, **kwargs)
AttributeError: 'AntMazeEnv' object has no attribute 'wrapped_env'
Exception ignored in: <bound method Env.__del__ of <goal_env.mujoco.ant.AntEnv object at 0x000000002DAC8A90>>
Traceback (most recent call last):
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\core.py", line 202, in __del__
    self.close()
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\core.py", line 167, in close
    self.render(close=True)
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\core.py", line 153, in render
    return self._render(mode=mode, close=close)
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\envs\mujoco\mujoco_env.py", line 104, in _render
    if self.viewer is not None:
AttributeError: 'AntEnv' object has no attribute 'viewer'
Exception ignored in: <bound method Env.__del__ of <goal_env.mujoco.ant_maze_env.AntMazeEnv object at 0x0000000003B27240>>
Traceback (most recent call last):
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\core.py", line 202, in __del__
    self.close()
  File "D:\Anaconda\envs\AntEnv\lib\site-packages\gym\core.py", line 167, in close
    self.render(close=True)
  File "D:\2020Grade_three\2021_grade_proj\HRL_code\Lesson\LESSON-master\goal_env\mujoco\maze_env.py", line 492, in render
    return self.wrapped_env.render(*args, **kwargs)
AttributeError: 'AntMazeEnv' object has no attribute 'wrapped_env'
```
and my env setting:
platform:win10
python:3.6.13
gym:0.9.1
mujoco_py:0.5.7
mjpro131
torch:1.8.1
Do you know how to solve this problem? thank you

**Comment by SiyuanLee** [comment]
Maybe because the gym version is too old. The gym version I use is 0.10.3.

**Comment by rainandwind1** [comment]
Ok, thanks for replaying me, i will take your advice and have a try.
